AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/**/*'
    - '**/vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*_spec.rb'
    - '**/*.gemspec'
    - '**/*.rake'

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/FirstArgumentIndentation:
  Enabled: true
Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line
Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Enabled: true
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/UriEscapeUnescape:
  Enabled: false
