AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/NumericLiterals:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose
